### ISSUE TITLE
Python 3.8 deployment: Invalid requirement: 'scikit_learn~1.0.1'

### ISSUE THREAD

**Issue by frankpacini** [aws/aws-elastic-beanstalk-cli#176]
### Description

I am trying to deploy a Flask app with a Python 3.7 environment and get an error about `Invalid requirement: 'scikit_learn~1.0.1' on line 9 of the requirements.txt`. scikit-learn is an included module in my requirements.txt but it is not version 1.0.1 or line 9 of the file, and the error occurs whether I include that dependency or not. I checked that scikit-learn is also not a dependency of any of the other packages.

### Steps to reproduce
To create the environment I am running:
`eb create -r us-east-1 aneda-env -i t4g.small -ix 1 --debug`

The requirements.txt file generated with `pipreqs` is:

```
dgl==0.9.0
dill==0.3.5.1
Flask==2.0.3
Flask_Cors==3.0.10
folium==0.0.0
Jinja2==3.1.2
matplotlib==3.5.0
networkx==2.8
numpy==1.22.0
osmnx==1.1.0
pandas==1.4.0
PyYAML==5.4.1
requests==2.26.0
scipy==1.6.2
torch==1.12.1
torchsummary==1.5.1
tqdm==4.59.0
trainer==0.0.13
```

and my config.yml is:

```
branch-defaults:
  deploy:
    environment: aneda-env
    group_suffix: null
global:
  application_name: ANEDA
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
```
No other configuration files are in use and I am following these instructions: https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create-deploy-python-flask.html

### Observed result

![image](https://user-images.githubusercontent.com/32715673/183553933-654f7521-4c8c-42b7-aa0b-c4202a4da12d.png)

### Expected result

The deployment should be successful or have errors that are related to my configuration.

### Additional environment details

1. OS: Ubuntu 20.04 VM
2. EBCLI version: 3.20.3 (Python 3.8.8)
3. Platform version: 3.3.16
