### ISSUE TITLE
Unsupported platform

### ISSUE THREAD

**Issue by purdy** [aws/aws-elastic-beanstalk-cli#513]
Similar to #32 ...

I'm running into this issue where my config .yml looks like this:

```yml
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-1::platform/PHP 8.2 running on 64bit
    Amazon Linux 2023/4.0.1
```

And when I run `eb platform show`, it doesn't get the full platform name:

```
% eb platform show
ERROR: NotFoundError - Elastic Beanstalk can't find a platform version that matches "PHP 8.1 running on 64bit Amazon Linux 2".
```

It'd be nice if we could just say something like:

```yml
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-1::platform/php-8.2
```

After all, if I do a `eb platform list`, that's what shows up.
